#!/usr/bin/env python3
"""
Chronos-2 Fine-Tuning with SarSim0 Synthetic Data.

This script fine-tunes Chronos-2 on synthetic time series generated by SarSim0.
Supports both full fine-tuning and LoRA fine-tuning.
Uses on-the-fly data generation with multiple workers for infinite data variety.

Usage:
    python train_chronos2.py --num_steps 1000 --batch_size 32 --finetune_mode lora
    python train_chronos2.py --num_steps 5000 --batch_size 64 --finetune_mode full
"""

import argparse
import os
import sys
import time
import warnings
from pathlib import Path
from typing import Iterator

# Add sarsim0 to path
sys.path.insert(0, str(Path(__file__).parent.parent))

import torch
import torch.utils.data
import numpy as np

from chronos import BaseChronosPipeline, Chronos2Pipeline
from chronos.chronos2.dataset import Chronos2Dataset, DatasetMode

from sarsim0 import SarSimConfig
from sarsim0.covariates import generate_mixed_with_covariates


def disable_rope(pipeline) -> int:
    """
    Disable RoPE (Rotary Position Embedding) for DroPE fine-tuning.

    DroPE (Dropping Positional Encoding) removes positional embeddings after pretraining
    to enable better length generalization. See: https://pub.sakana.ai/DroPE/

    Args:
        pipeline: The Chronos2Pipeline to modify

    Returns:
        Number of attention layers modified
    """
    # Set config flag for consistency
    pipeline.model.config.use_rope = False

    # Apply to all MHA modules (needed because model was already instantiated)
    count = 0
    for module in pipeline.model.modules():
        if hasattr(module, 'use_rope') and module.use_rope:
            module.use_rope = False
            if hasattr(module, 'rope_embed'):
                del module.rope_embed
            count += 1
    return count


class SarSim0StreamingChronos2Dataset(torch.utils.data.IterableDataset):
    """
    Streaming dataset that generates SarSim0 time series on-the-fly for Chronos-2 training.

    Unlike loading all data upfront, this generates fresh batches continuously during training.
    Compatible with Chronos2Trainer which expects an IterableDataset yielding batch dicts.
    """

    def __init__(
        self,
        context_length: int,
        prediction_length: int,
        batch_size: int,
        output_patch_size: int,
        multivariate_prob: float = 0.3,
        with_covariates_prob: float = 0.3,
        base_seed: int = 42,
    ):
        super().__init__()
        self.context_length = context_length
        self.prediction_length = prediction_length
        self.batch_size = batch_size
        self.output_patch_size = output_patch_size
        self.num_output_patches = (prediction_length + output_patch_size - 1) // output_patch_size
        self.multivariate_prob = multivariate_prob
        self.with_covariates_prob = with_covariates_prob
        self.base_seed = base_seed

        self.config = SarSimConfig(
            series_length=context_length + prediction_length + 200,
            context_window=context_length,
            prediction_window=prediction_length,
            burn_in=200,
            multivariate_prob=multivariate_prob,
            n_variates_range=(2, 5),
            with_covariates_prob=with_covariates_prob,
            n_past_covariates_range=(0, 3),
            n_future_covariates_range=(0, 2),
        )

    def _prepare_single_task(self, sample: dict) -> tuple:
        """Convert a SarSim0 sample to Chronos-2 task format."""
        target = sample["target"]
        if isinstance(target, np.ndarray):
            target = torch.from_numpy(target).float()
        if target.ndim == 1:
            target = target.unsqueeze(0)  # (1, length)

        n_targets = target.shape[0]
        past_covariates = sample.get("past_covariates", {})
        future_covariates = sample.get("future_covariates", {})

        # Build past tensor: targets + past-only covs + future covs (past values)
        past_tensors = [target]
        past_only_cov_names = set(past_covariates.keys()) - set(future_covariates.keys())
        future_cov_names = list(future_covariates.keys())

        # Add past-only covariates
        for name in sorted(past_only_cov_names):
            cov = past_covariates[name]
            if isinstance(cov, np.ndarray):
                cov = torch.from_numpy(cov).float()
            past_tensors.append(cov.unsqueeze(0))

        # Add future covariates (past values)
        for name in future_cov_names:
            cov = past_covariates[name]
            if isinstance(cov, np.ndarray):
                cov = torch.from_numpy(cov).float()
            past_tensors.append(cov.unsqueeze(0))

        task_past = torch.cat(past_tensors, dim=0)  # (n_series, length)

        # Build future tensor for future covariates
        future_tensors = []
        for name in future_cov_names:
            fcov = future_covariates[name]
            if isinstance(fcov, np.ndarray):
                fcov = torch.from_numpy(fcov).float()
            future_tensors.append(fcov.unsqueeze(0))

        if future_tensors:
            task_future = torch.cat(future_tensors, dim=0)
        else:
            task_future = torch.zeros((0, self.prediction_length))

        n_covariates = len(past_only_cov_names) + len(future_cov_names)
        n_future_covariates = len(future_cov_names)

        return task_past, task_future, n_targets, n_covariates, n_future_covariates

    def _build_batch(self, samples: list[dict]) -> dict:
        """Build a Chronos-2 compatible batch from samples."""
        batch_context_list = []
        batch_future_target_list = []
        batch_future_covariates_list = []
        batch_group_ids_list = []

        for group_id, sample in enumerate(samples):
            task_past, task_future, n_targets, n_covariates, n_future_covariates = self._prepare_single_task(sample)
            n_past_only = n_covariates - n_future_covariates

            full_length = task_past.shape[-1]

            # Random slice for training
            min_past = self.prediction_length
            slice_idx = np.random.randint(min_past, full_length - self.prediction_length + 1)

            # Context
            if slice_idx >= self.context_length:
                context = task_past[:, slice_idx - self.context_length : slice_idx]
            else:
                context = task_past[:, :slice_idx]

            # Future target
            future_target = task_past[:, slice_idx : slice_idx + self.prediction_length].clone()
            future_target[n_targets:] = torch.nan  # Mask covariates

            # Future covariates
            if n_future_covariates > 0:
                future_covs = task_past[-n_future_covariates:, slice_idx : slice_idx + self.prediction_length]
            else:
                future_covs = torch.zeros((0, self.prediction_length))

            # Padding for targets and past-only covariates
            padding = torch.full((n_targets + n_past_only, self.prediction_length), torch.nan)
            future_covariates = torch.cat([padding, future_covs], dim=0)

            group_size = context.shape[0]
            group_ids = torch.full((group_size,), fill_value=group_id)

            batch_context_list.append(context)
            batch_future_target_list.append(future_target)
            batch_future_covariates_list.append(future_covariates)
            batch_group_ids_list.append(group_ids)

        # Left-pad and concatenate contexts
        max_len = max(c.shape[-1] for c in batch_context_list)
        padded_contexts = []
        for c in batch_context_list:
            if c.shape[-1] < max_len:
                pad = torch.full((c.shape[0], max_len - c.shape[-1]), torch.nan)
                c = torch.cat([pad, c], dim=-1)
            padded_contexts.append(c)

        return {
            "context": torch.cat(padded_contexts, dim=0),
            "future_target": torch.cat(batch_future_target_list, dim=0),
            "future_covariates": torch.cat(batch_future_covariates_list, dim=0),
            "group_ids": torch.cat(batch_group_ids_list, dim=0),
            "num_output_patches": self.num_output_patches,
        }

    def __iter__(self) -> Iterator[dict]:
        """Generate infinite stream of batches for training."""
        # Use time-based seed for variety across runs
        seed = self.base_seed + int(time.time() * 1000) % (2**20)
        generator = torch.Generator(device="cpu")
        generator.manual_seed(seed)

        batch_num = 0
        while True:
            # Generate fresh samples for this batch
            samples = generate_mixed_with_covariates(
                batch_size=self.batch_size,
                context_length=self.context_length,
                prediction_length=self.prediction_length,
                config=self.config,
                generator=generator,
            )

            yield self._build_batch(samples)
            batch_num += 1

            # Re-seed periodically for more variety
            if batch_num % 1000 == 0:
                generator.manual_seed(seed + batch_num)


def generate_training_data(
    num_series: int,
    context_length: int,
    prediction_length: int,
    seed: int = 42,
    multivariate_prob: float = 0.3,
    with_covariates_prob: float = 0.3,
) -> list[dict]:
    """
    Generate mixed training data from SarSim0 with covariates support.
    Used for validation data (fixed dataset).
    """
    config = SarSimConfig(
        series_length=context_length + prediction_length + 200,
        context_window=context_length,
        prediction_window=prediction_length,
        burn_in=200,
        multivariate_prob=multivariate_prob,
        n_variates_range=(2, 5),
        with_covariates_prob=with_covariates_prob,
        n_past_covariates_range=(0, 3),
        n_future_covariates_range=(0, 2),
    )

    generator = torch.Generator(device="cpu")
    generator.manual_seed(seed)

    return generate_mixed_with_covariates(
        batch_size=num_series,
        context_length=context_length,
        prediction_length=prediction_length,
        config=config,
        generator=generator,
    )


def main():
    parser = argparse.ArgumentParser(
        description="Fine-tune Chronos-2 on SarSim0 synthetic data"
    )

    # Model arguments
    parser.add_argument(
        "--model_id",
        type=str,
        default="amazon/chronos-2",
        help="Pretrained model ID (default: amazon/chronos-2)",
    )
    parser.add_argument(
        "--device_map",
        type=str,
        default="cuda" if torch.cuda.is_available() else "cpu",
        help="Device to use (default: cuda if available)",
    )

    # Data arguments
    parser.add_argument(
        "--num_train_samples",
        type=int,
        default=10000,
        help="Number of training samples - ignored in streaming mode (default: 10000)",
    )
    parser.add_argument(
        "--num_val_series",
        type=int,
        default=1000,
        help="Number of validation series (fixed, default: 1000)",
    )
    parser.add_argument(
        "--context_length",
        type=int,
        default=512,
        help="Context length for training (default: 512)",
    )
    parser.add_argument(
        "--prediction_length",
        type=int,
        default=64,
        help="Prediction length for training (default: 64)",
    )
    parser.add_argument(
        "--multivariate_prob",
        type=float,
        default=0.3,
        help="Probability of multivariate vs univariate samples (default: 0.3)",
    )
    parser.add_argument(
        "--with_covariates_prob",
        type=float,
        default=0.3,
        help="Probability of including covariates (default: 0.3)",
    )
    parser.add_argument(
        "--num_workers",
        type=int,
        default=4,
        help="Number of data loading workers (default: 4)",
    )

    # Training arguments
    parser.add_argument(
        "--finetune_mode",
        type=str,
        choices=["full", "lora"],
        default="lora",
        help="Fine-tuning mode (default: lora)",
    )
    parser.add_argument(
        "--num_steps",
        type=int,
        default=1000,
        help="Number of training steps (default: 1000)",
    )
    parser.add_argument(
        "--batch_size",
        type=int,
        default=32,
        help="Batch size for training (default: 32)",
    )
    parser.add_argument(
        "--learning_rate",
        type=float,
        default=None,
        help="Learning rate (default: 1e-5 for full, 1e-4 for lora)",
    )
    parser.add_argument(
        "--logging_steps",
        type=int,
        default=100,
        help="Logging frequency (default: 100)",
    )
    parser.add_argument(
        "--refresh_data_every",
        type=int,
        default=0,
        help="Refresh training data every N steps (0 = no refresh, default: 0)",
    )

    # Output arguments
    parser.add_argument(
        "--output_dir",
        type=str,
        default="./chronos2-sarsim0-finetuned",
        help="Output directory for fine-tuned model (default: ./chronos2-sarsim0-finetuned)",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed (default: 42)",
    )
    parser.add_argument(
        "--drope",
        action="store_true",
        default=True,
        help="Enable DroPE (Dropping Positional Encoding) - disable RoPE for fine-tuning (default: True)",
    )
    parser.add_argument(
        "--streaming",
        action="store_true",
        default=False,
        help="Use streaming data generation with multiple workers (default: False)",
    )
    parser.add_argument(
        "--bf16",
        action="store_true",
        default=True,
        help="Use bfloat16 mixed precision training (default: True, requires SM >= 8.0)",
    )
    parser.add_argument(
        "--no-bf16",
        action="store_true",
        default=False,
        help="Disable bfloat16, use float32 instead",
    )

    args = parser.parse_args()

    # Handle bf16 flag
    if args.no_bf16:
        args.bf16 = False

    # Set default learning rate based on finetune mode
    if args.learning_rate is None:
        args.learning_rate = 1e-4 if args.finetune_mode == "lora" else 1e-5

    print("=" * 60)
    print("Chronos-2 Fine-Tuning with SarSim0")
    print("=" * 60)
    print(f"Model: {args.model_id}")
    print(f"Device: {args.device_map}")
    print(f"Fine-tune mode: {args.finetune_mode}")
    if args.streaming:
        num_train_samples = args.num_steps * args.batch_size
        print(f"Training samples: {num_train_samples} (streaming: num_steps * batch_size)")
    else:
        num_train_samples = args.num_train_samples
        print(f"Training samples: {num_train_samples}")
    print(f"Validation series: {args.num_val_series}")
    print(f"Context length: {args.context_length}")
    print(f"Prediction length: {args.prediction_length}")
    print(f"Multivariate prob: {args.multivariate_prob}")
    print(f"With covariates prob: {args.with_covariates_prob}")
    print(f"Batch size: {args.batch_size}")
    print(f"Learning rate: {args.learning_rate}")
    print(f"Num steps: {args.num_steps}")
    print(f"DroPE (disable RoPE): {args.drope}")
    print(f"Streaming mode: {args.streaming}")
    print(f"Num workers: {args.num_workers}")
    print(f"bf16: {args.bf16}")
    if args.refresh_data_every > 0:
        print(f"Data refresh: every {args.refresh_data_every} steps")
    print()

    # Load pretrained model
    print("Loading pretrained Chronos-2 model...")
    pipeline: Chronos2Pipeline = BaseChronosPipeline.from_pretrained(
        args.model_id,
        device_map=args.device_map,
    )
    print("Model loaded.")

    # Apply DroPE - disable RoPE for fine-tuning
    if args.drope:
        num_modified = disable_rope(pipeline)
        print(f"DroPE enabled: disabled RoPE on {num_modified} attention layers.")
    print()

    # Generate validation data (fixed)
    print(f"Generating {args.num_val_series} validation series (fixed)...")
    val_inputs = generate_training_data(
        num_series=args.num_val_series,
        context_length=args.context_length,
        prediction_length=args.prediction_length,
        seed=args.seed + 1000,
        multivariate_prob=args.multivariate_prob,
        with_covariates_prob=args.with_covariates_prob,
    )
    n_uni_val = sum(1 for inp in val_inputs if inp["target"].ndim == 1)
    n_multi_val = len(val_inputs) - n_uni_val
    n_with_cov_val = sum(1 for inp in val_inputs if "past_covariates" in inp or "future_covariates" in inp)
    print(f"  - {n_uni_val} univariate, {n_multi_val} multivariate")
    print(f"  - {n_with_cov_val} with covariates, {len(val_inputs) - n_with_cov_val} without")
    print()

    if args.streaming:
        # Streaming mode: generate fresh data on-the-fly during training
        # Uses a custom IterableDataset that produces infinite batches
        print(f"Streaming mode: generating fresh data on-the-fly")
        print(f"Total steps: {args.num_steps}")
        print("-" * 60)

        # Import trainer components
        from copy import deepcopy
        from transformers.training_args import TrainingArguments
        from chronos.chronos2.trainer import Chronos2Trainer, EvaluateAndSaveFinalStepCallback
        from chronos.chronos2.model import Chronos2Model
        from chronos.chronos2.dataset import Chronos2Dataset, DatasetMode

        if args.finetune_mode == "lora":
            from peft import LoraConfig, get_peft_model

        # Create a copy of the model
        config = deepcopy(pipeline.model.config)
        model = Chronos2Model(config).to(pipeline.model.device)
        model.load_state_dict(pipeline.model.state_dict())

        # Apply LoRA if needed
        if args.finetune_mode == "lora":
            lora_config = LoraConfig(
                r=8,
                lora_alpha=16,
                target_modules=[
                    "self_attention.q",
                    "self_attention.v",
                    "self_attention.k",
                    "self_attention.o",
                    "output_patch_embedding.output_layer",
                ],
            )
            model = get_peft_model(model, lora_config)
            n_trainable, n_total = model.get_nb_trainable_parameters()
            print(f"LoRA: {n_trainable:,} trainable / {n_total:,} total params")

        # Create streaming training dataset
        output_patch_size = pipeline.model.chronos_config.output_patch_size
        train_dataset = SarSim0StreamingChronos2Dataset(
            context_length=args.context_length,
            prediction_length=args.prediction_length,
            batch_size=args.batch_size,
            output_patch_size=output_patch_size,
            multivariate_prob=args.multivariate_prob,
            with_covariates_prob=args.with_covariates_prob,
            base_seed=args.seed,
        )

        # Create validation dataset (fixed)
        eval_dataset = Chronos2Dataset.convert_inputs(
            inputs=val_inputs,
            context_length=args.context_length,
            prediction_length=args.prediction_length,
            batch_size=args.batch_size,
            output_patch_size=output_patch_size,
            mode=DatasetMode.VALIDATION,
        )

        # Setup training arguments
        output_dir = Path(args.output_dir) / "streaming-run"
        use_cpu = str(pipeline.model.device) == "cpu"
        use_bf16 = args.bf16 and not use_cpu

        if use_bf16:
            has_sm80 = torch.cuda.is_available() and torch.cuda.get_device_capability()[0] >= 8
            if not has_sm80:
                print("Warning: bf16 requested but GPU does not support it (SM < 8.0). Using fp32.")
                use_bf16 = False

        training_args = TrainingArguments(
            output_dir=str(output_dir),
            per_device_train_batch_size=1,  # Dataset already batches
            per_device_eval_batch_size=args.batch_size,
            learning_rate=args.learning_rate,
            lr_scheduler_type="linear",
            warmup_ratio=0.0,
            optim="adamw_torch_fused",
            logging_strategy="steps",
            logging_steps=args.logging_steps,
            disable_tqdm=False,
            report_to="none",
            max_steps=args.num_steps,
            gradient_accumulation_steps=1,
            dataloader_num_workers=0,
            tf32=use_bf16,  # tf32 also requires SM >= 8.0
            bf16=use_bf16,
            save_only_model=True,
            prediction_loss_only=True,
            save_total_limit=1,
            save_strategy="steps",
            save_steps=args.logging_steps,
            eval_strategy="steps",
            eval_steps=args.logging_steps,
            load_best_model_at_end=True,
            metric_for_best_model="eval_loss",
            label_names=["future_target"],
            use_cpu=use_cpu,
        )

        if not use_cpu:
            training_args._n_gpu = 1

        # Create trainer
        callbacks = [EvaluateAndSaveFinalStepCallback()]
        trainer = Chronos2Trainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=eval_dataset,
            callbacks=callbacks,
        )

        print("\nStarting streaming training...")
        trainer.train()

        # Save final model
        print(f"\nSaving model to {args.output_dir}...")
        os.makedirs(args.output_dir, exist_ok=True)

        # Get the final model and create pipeline
        final_model = trainer.model
        if hasattr(final_model, 'merge_and_unload'):
            final_model = final_model.merge_and_unload()

        finetuned_pipeline = Chronos2Pipeline(final_model)

    else:
        # Standard mode: generate all data upfront
        print(f"Generating {num_train_samples} training series...")
        train_inputs = generate_training_data(
            num_series=num_train_samples,
            context_length=args.context_length,
            prediction_length=args.prediction_length,
            seed=args.seed,
            multivariate_prob=args.multivariate_prob,
            with_covariates_prob=args.with_covariates_prob,
        )

        # Count statistics
        n_uni = sum(1 for inp in train_inputs if inp["target"].ndim == 1)
        n_multi = len(train_inputs) - n_uni
        n_with_cov = sum(1 for inp in train_inputs if "past_covariates" in inp or "future_covariates" in inp)
        print(f"Generated {len(train_inputs)} training series:")
        print(f"  - {n_uni} univariate, {n_multi} multivariate")
        print(f"  - {n_with_cov} with covariates, {len(train_inputs) - n_with_cov} without")
        print()

        print("Starting fine-tuning...")
        print("-" * 60)

        finetuned_pipeline = pipeline.fit(
            inputs=train_inputs,
            validation_inputs=val_inputs,
            prediction_length=args.prediction_length,
            finetune_mode=args.finetune_mode,
            num_steps=args.num_steps,
            batch_size=args.batch_size,
            learning_rate=args.learning_rate,
            logging_steps=args.logging_steps,
        )

    print("-" * 60)
    print("Fine-tuning complete!")
    print()

    # Save the fine-tuned model
    print(f"Saving fine-tuned model to {args.output_dir}...")
    os.makedirs(args.output_dir, exist_ok=True)
    finetuned_pipeline.save_pretrained(args.output_dir)
    print("Model saved.")
    print()

    # Quick validation
    print("Running quick validation...")
    test_inputs = generate_training_data(
        num_series=10,
        context_length=args.context_length,
        prediction_length=args.prediction_length,
        seed=args.seed + 2000,
        multivariate_prob=args.multivariate_prob,
        with_covariates_prob=args.with_covariates_prob,
    )

    # Run predictions on first 3 samples
    print("Validation results:")
    for i, inp in enumerate(test_inputs[:3]):
        target = inp["target"]

        # Extract context from target
        if target.ndim == 1:
            context = target[: args.context_length]
            var_type = "univariate"
        else:
            context = target[:, : args.context_length]
            var_type = f"multivariate ({target.shape[0]} vars)"

        # Build prediction input with covariates if present
        pred_input = {"target": context}

        # Add past covariates if present (slice to context_length for inference)
        if "past_covariates" in inp:
            pred_input["past_covariates"] = {
                k: v[: args.context_length] for k, v in inp["past_covariates"].items()
            }

        # Add future covariates if present (already prediction_length)
        if "future_covariates" in inp:
            pred_input["future_covariates"] = inp["future_covariates"]

        has_cov = "past_covariates" in inp or "future_covariates" in inp
        cov_str = " +cov" if has_cov else ""

        quantiles, mean = finetuned_pipeline.predict_quantiles(
            [pred_input],
            prediction_length=args.prediction_length,
            quantile_levels=[0.1, 0.5, 0.9],
        )
        print(f"  Sample {i} ({var_type}{cov_str}): pred shape={mean[0].shape}, range=[{mean[0].min():.2f}, {mean[0].max():.2f}]")
    print()

    print("=" * 60)
    print("Done!")
    print("=" * 60)


if __name__ == "__main__":
    main()
